<?php
return array (
  26 => 
  array (
    'catid' => '26',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '12',
    'arrparentid' => '0,12',
    'child' => '0',
    'arrchildid' => '26',
    'catname' => '场地项目课程',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'content/',
    'catdir' => 'nn',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=26',
    'items' => '9',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -servive","list_template":"list -servive","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '26',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'changdixiangmukecheng',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  27 => 
  array (
    'catid' => '27',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '12',
    'arrparentid' => '0,12',
    'child' => '0',
    'arrchildid' => '27',
    'catname' => '高空项目课程',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'content/',
    'catdir' => 'high',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=27',
    'items' => '4',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -servive","list_template":"list -servive","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '27',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gaokongxiangmukecheng',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  28 => 
  array (
    'catid' => '28',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '12',
    'arrparentid' => '0,12',
    'child' => '0',
    'arrchildid' => '28',
    'catname' => '水上项目课程',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'content/',
    'catdir' => 'water',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=28',
    'items' => '4',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -servive","list_template":"list -servive","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '28',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'shuishangxiangmukecheng',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  29 => 
  array (
    'catid' => '29',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '12',
    'arrparentid' => '0,12',
    'child' => '0',
    'arrchildid' => '29',
    'catname' => '野外项目课程',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'content/',
    'catdir' => 'widd',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=29',
    'items' => '9',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -servive","list_template":"list -servive","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '29',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yewaixiangmukecheng',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  30 => 
  array (
    'catid' => '30',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '12',
    'arrparentid' => '0,12',
    'child' => '0',
    'arrchildid' => '30',
    'catname' => '趣味运动会课程',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'content/',
    'catdir' => 'ww',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=30',
    'items' => '9',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -servive","list_template":"list -servive","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '30',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'quweiyundonghuikecheng',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>