<?php
return array (
  16 => 
  array (
    'catid' => '16',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '16',
    'catname' => '公司简介',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'ABOUTUS/',
    'catdir' => 'sd',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=16',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '16',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gongsijianjie',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  17 => 
  array (
    'catid' => '17',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '17',
    'catname' => '企业理念',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'ABOUTUS/',
    'catdir' => 'linian',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=17',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '17',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'qiyelinian',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  18 => 
  array (
    'catid' => '18',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '18',
    'catname' => '关于拓展',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'ABOUTUS/',
    'catdir' => 'ele',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=18',
    'items' => '3',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '18',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'guanyutuozhan',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>