<?php
return array (
  19 => 
  array (
    'catid' => '19',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '10',
    'arrparentid' => '0,10',
    'child' => '0',
    'arrchildid' => '19',
    'catname' => '成功案例',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'SUCCESSCASE/',
    'catdir' => 'case',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=19',
    'items' => '12',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -success","list_template":"list-success","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '19',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'chenggonganli',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  20 => 
  array (
    'catid' => '20',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '10',
    'arrparentid' => '0,10',
    'child' => '0',
    'arrchildid' => '20',
    'catname' => '视频文件',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'SUCCESSCASE/',
    'catdir' => 'video',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=20',
    'items' => '3',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -success","list_template":"list-success","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '20',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'shipinwenjian',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>