<?php
return array (
  21 => 
  array (
    'catid' => '21',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '11',
    'arrparentid' => '0,11',
    'child' => '0',
    'arrchildid' => '21',
    'catname' => '专业拓展训练',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'servive/',
    'catdir' => 's',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=21',
    'items' => '5',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -servive","list_template":"list -servive","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '21',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'zhuanyetuozhanxunlian',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  22 => 
  array (
    'catid' => '22',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '11',
    'arrparentid' => '0,11',
    'child' => '0',
    'arrchildid' => '22',
    'catname' => '军事拓展训练',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'servive/',
    'catdir' => 'sd',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=22',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -servive","list_template":"list -servive","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '22',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'junshituozhanxunlian',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  23 => 
  array (
    'catid' => '23',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '11',
    'arrparentid' => '0,11',
    'child' => '0',
    'arrchildid' => '23',
    'catname' => '趣味运动会',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'servive/',
    'catdir' => 'sport',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=23',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -servive","list_template":"list -servive","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '23',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'quweiyundonghui',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  24 => 
  array (
    'catid' => '24',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '11',
    'arrparentid' => '0,11',
    'child' => '0',
    'arrchildid' => '24',
    'catname' => '野外拓展',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'servive/',
    'catdir' => 'wide',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=24',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -servive","list_template":"list -servive","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '24',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yewaituozhan',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  25 => 
  array (
    'catid' => '25',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '11',
    'arrparentid' => '0,11',
    'child' => '0',
    'arrchildid' => '25',
    'catname' => '场地拓展',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'servive/',
    'catdir' => 'hh',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=25',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category -servive","list_template":"list -servive","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '25',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'changdituozhan',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>