<?php
return array (
  31 => 
  array (
    'catid' => '31',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '1',
    'parentid' => '13',
    'arrparentid' => '0,13',
    'child' => '0',
    'arrchildid' => '31',
    'catname' => '安全保障',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'safe/',
    'catdir' => 'safety',
    'url' => 'http://localhost/tysl/index.php?m=content&c=index&a=lists&catid=31',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '31',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'anquanbaozhang',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>